travis:
  secure:
    BINSTAR_TOKEN: H5RZFBuKQtRTM7/9fjd+zx8byau+kHBp0Quk4BOpAVV/KS2NkRbrfhr087Swwf/fThyZkDtP61CXZ4KchkGLBpa3otguGfTvAXA9qTQg/KaGTnwMG5oa84W0U//mKTq/RcbuImcq2PI8H8aISM9kkNVNXQHM10pw5ouhQ2RYdQsXYqdAr+p2pUDUuWMfRnvLk2DoCynv1yLbERofopIF5jEfHGiXdIhkhfDH4WCVqNqPdrc7D6zZV+sLWKMzgVETes+5kqKu1Cc1em0SrJPVHODZ9J16wu+uXQwhquelHWmvCLNBvaXc/mRhzs/RXdGnFpeTK8gg3GObeI/axHXWACEmYKouIo6mnCaHjRZE/bUOMKWEvkF45CvNtlZJpgpjtdpm6PgtK8VwQiAKvvodZ/eDxiEBw812OFAD0alAwpmdlqEnmaHykHhoUWiGjUWs/jwElgqW0ia09IKUYSPJw2RF9BdHD36E7kuQbtVlMiwGsIuT5g6xMBBRu5ueY1PFKYvYytKNDQppfIZUTk2+ZpfvRlGkBSL8a0hL3vSC0N95vIOAvBtigaiLFwZvvu3dof89vh9QDL/T4Z8qQz1MzuD20yMYBdqLstfqI5bliFNFoI+jI0H8oqFP3PcA9DS0C867MxSFzjFdZnQKf0fzD/pjHFVJ6hPKU8sGkWQQ35o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
