travis:
  secure:
    BINSTAR_TOKEN: Kuyrdta8/FB37hI91TUmY4oiJ2wsBIQHLh5rBW4xpr56ybVSh2RuML9qg0z9E+vx8kYGwqWzShzvaWK62RoFDUb2bEDFXsZwLTG2pyztIRkiK29Yr7aPrBCPmJb0UXnbIHTANbSmJs/6rBLJyNe1FUBMyEupYLHfx6JdLnxkPmRMqiPzE20rpQnnPv43RszxeyUmmu0BQYOLNBsePZ2b0wuSMUy9fes4wx3A5Er+5HTufGvbgVDBaxlL0f7W71R6CVqx+Rn/rNTyvPTijYtV6MiqPgGFLsWu0A9PlPMVFEz8DXi0oxHn6EMv3uDKNaH2xnmnbUgWt5MqHUqbTVRPV9TdSlaxtAzdebxEAWYryJAUjETfZ5u4ZiYrDEx+9cDqF9vkrmpcv1DokOGnAHXmAypO0P6LmP4hAh5I2vq3P4viltuOEgTd7k+tN3fs9vB0fgIHqwDn5hjQEbxBw1bXadhViiL0Sdf+Y0OgaSsj2uvzfL9AlLmVYpoiR2psUvdFCdMhIkE4evPEqsWFHhiR9VQp6HhT0xDBAbfRnUdg+uEPvjgcOrtOdMmm/V+8+CZMheegpvugq2sYPadPP4t4O8iHZZQsnspD4gOwY19OQxMCDQRNFi6CV2qBJsX3VreMCtbA2DKEDUDJ+V4FV+v0Zjea2uM3YG2xmSBZQZTtqzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
